# Generated by Django 5.1.4 on 2024-12-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('is_key_exhausted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'APIkey',
                'verbose_name_plural': 'APIkeys',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(default=None, max_length=255)),
                ('channel_title', models.CharField(default=None, max_length=255)),
                ('video_id', models.CharField(default=None, max_length=255)),
                ('video_title', models.CharField(default=None, max_length=255)),
                ('video_description', models.CharField(default=None, max_length=255)),
                ('pub_date', models.DateTimeField()),
                ('thumb_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
